// Copyright (c) 2018-2020 Double.  All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

const SYS_JUGLANS_SCAN_BEFORE = 'SYS_JUGLANS_SCAN_BEFORE'
const SYS_JUGLANS_SCAN_AFTER = 'SYS_JUGLANS_SCAN_AFTER'
const SYS_JUGLANS_PLUGINS_HTTPPROXY_LISTEN_FAILED = 'SYS_JUGLANS_PLUGINS_HTTPPROXY_LISTEN_FAILED'
const SYS_JUGLANS_PLUGINS_HTTPPROXY_LISTEN_SUCCEED = 'SYS_JUGLANS_PLUGINS_HTTPPROXY_LISTEN_SUCCEED'

const events = {
  [SYS_JUGLANS_SCAN_BEFORE]: SYS_JUGLANS_SCAN_BEFORE,
  [SYS_JUGLANS_SCAN_AFTER]: SYS_JUGLANS_SCAN_AFTER,
  [SYS_JUGLANS_PLUGINS_HTTPPROXY_LISTEN_FAILED]: SYS_JUGLANS_PLUGINS_HTTPPROXY_LISTEN_FAILED,
  [SYS_JUGLANS_PLUGINS_HTTPPROXY_LISTEN_SUCCEED]: SYS_JUGLANS_PLUGINS_HTTPPROXY_LISTEN_SUCCEED
}

module.exports = events
